name: CI
on: ['push', 'pull_request']
jobs:
  build_and_test:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    
    steps:
      - uses: actions/checkout@v4

      - name: Rye
        uses: eifinger/setup-rye@v3
        with:
          version: 'latest'

      - name: Test
        run: rye test
